name: Deploy Sphinx documentation to Pages


on:
  release:
    types: [published]
  workflow_dispatch:
  workflow_run:
    workflows: python-publish
    
jobs:
  build:
    name: Push Sphinx Pages
    runs-on: ubuntu-latest
    steps:
    - uses: seanzhengw/sphinx-pages@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        create_readme: true
